name: Other platform builds

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-android:
    name: Build (Android)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: src/android/frontend/gradle/wrapper/gradle-wrapper.properties

      - name: Install ccache
        run: sudo apt-get update && sudo apt-get install -y ccache

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-android-${{ github.sha }}
          restore-keys: |
            ccache-android-

      - name: Fix FMOD path structure
        run: |
          if [ -d "vendor/vendor/fmod" ]; then
            echo "Ajustando caminho da pasta FMOD..."
            rm -rf vendor/fmod
            mv vendor/vendor/fmod vendor/fmod
          fi

      - name: Build APK
        run: |
          cd src/android/frontend
          ./gradlew assembleDebug \
            -Pandroid.cxx.ndk.ccache=true \
            -Porg.gradle.caching=true \
            -Pandroid.injected.build.abi=arm64-v8a \
            -Pbutterscotch.audio=fmod

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: butterscotch-android
          path: src/android/frontend/app/build/outputs/apk/debug/app-debug.apk
